### ISSUE TITLE
Wrong serial number from sensor

### ISSUE THREAD

**Issue by wiwild** [Sensirion/arduino-i2c-stc3x#1]
Serial number reads only 5 Bytes instead of 8 Bytes. The sensor does not send 8 bytes and timeout after 5bytes received.

Is this normal operation ? Are the 3 missing bytes left for future use ? Shouldn't they be sent by the sensor anyway even if they are 0 ?

Thank you

**Comment by psachs** [comment]
the command reads a 32-bit product identifier and a 64-bit serial number.
On a low level this means the sensor returns 18 bytes (every 2-byte word is followed with 1 byte CRC)

There is no reserved bytes and you should always get all data back from the sensor.
