### ISSUE TITLE
Low noise measurement mode not usable

### ISSUE THREAD

**Issue by thaintrinh** [Sensirion/arduino-i2c-stc3x#7]
Hello,
I'm using STC31-C to measure CO2 in N2. 
According to the datasheet on the website (I assume it's the newest one), **section 3.3.2** says that it can be used for low-noise measurement mode by setting the binary gas to 0x0000 - 0x0003.
In the code, line 60 of exampleUsage, I set BINARY_GAS to 0x0002 because I want to measure CO2 in N2.
Upon running, I get a NACK error as if the command is not recognizable.
Does this command only apply to STC31???
Please help.
Thanks.

**Comment by psachs** [comment]
Hi,

Yes you are correct, for the STC31-C you should be able to use the low noise commands as well according to the datasheet.
Unfortunately the sensor itself will not give you an error if a measurement command is not supported. I will have to try it with one of our samples to confirm if it works or not and will come back with an answer as soon as I know more.

**Comment by psachs** [comment]
I just tested with a sample of the STC31-C and could successfully execute all low noise binary gases from 0x0-0x3.
I can therefore confirm that the sensor supports all of the documented binary gases. If a gas is not supported you should see a "not enough data received" error and not a NACK error. I therefore assume something else in the communication is not stable.

Are you using the latest version of the Arduino driver 1.0.1?

**Comment by thaintrinh** [comment]
Hello,
Thanks for getting back to me. Indeed, I'm getting a "not enough data received" sorry for not clarifying that.
Where can I get 1.0.1? I'm using 1.0.0 which I downloaded from this repo.
Thanks alot.

**Comment by psachs** [comment]
Ok thanks for the clarification. Could you also verify that the binary gas commands 0x10-0x13 work with your sensor?
And the initialization of the sensor with the example works as well? It should print out the serial number and product id.

Can you also send me the output for the product id so I can verify which exact version of the STC31-C sensor you are using.

**Comment by thaintrinh** [comment]
I can confirm that with 0x10 - 0x13 command, the sensor works pretty much fine.
This is my serial number and product ID:
Product id = 8010304
Serial Number = 0x3550544E46000000

**Comment by psachs** [comment]
Thanks for the info.

I can confirm that you are using the same STC31-C sensor as I did for testing. There is also no reason why the low noise commands should not work while the other ones work unless the configuration for those binary gases are missing.

I have to ask the responsible product manager to ensure I don't miss anything.

**Comment by psachs** [comment]
Hi @thaintrinh 

Can you run the self test of the sensor and send me the result for further debugging? According to our engineers the low noise commands should work if the binary gas command is sent correctly.

```c++
    STC3xTestResultT selfTestOutput;
    error = sensor.selfTest(selfTestOutput);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute selfTest(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("Self Test result = ");
    Serial.print(selfTestOutput.value);
    Serial.println();
```

**Comment by psachs** [comment]
I close the ticket due to inactivity
